### ISSUE TITLE
it can only scan one url from the file.

### ISSUE THREAD

**Issue by darshan218** [ozzi-/consoleSSLlabs#4]
I am trying to scan urls from the file it can only scan one url and then it stops so please can you fix it.
Thank You

**Comment by ozzi-** [comment]
Quote from readme.MD:
    The url file must use the following format:
       One line only
       urls seperated by semicolon ;

Please make sure your urlfile follows this format, otherwise please post it for debugging purposes.

Cheers

**Comment by darshan218** [comment]
Hey

Actually i also tried with my csv file but the result is same its only
scanning one url and gives the result and then it stops so can you please
tell me solution or whats the problem.

Regards,
Darshan

**Comment by ozzi-** [comment]
Hi Darshan

Please use a text file, usinng the following format:
example.com;youtube.com;google.com

This works, otherwise feel free to change the code.
